---
title: "Running Rust in Rmd files with new knitr engine"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{rust-in-rmd}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(jordan)
```

Function sets the knitr rust engine

```{r set engine}
jordan::set_rust_engine()
# wrapper for: 
# knitr::knit_engines$set(rust = jordan::engine_rust)
```

## Rust

```{rust Simple rust}
fn main() {
  println!("Hello, world!");
}
```

```{rust Rust without depedencies}
use std::iter;

fn main() {
    let v = vec![1, 2, 3, 4, 5];
    v.iter().for_each(|x| println!("{}", x * 2));
}
```

## With depedencies

<!-- Will create file in the current wd: /vignettes -->

```{r Create toml}
text <- sprintf('
[package]
name = "%s"
version = "0.0.0"

[dependencies]
ferris-says = "0.2.0"
',
basename(getwd())
)
cat(text, file = "cargo.toml")
```

```{rust Rust with depedencies, toml=TRUE}
// https://docs.rs/ferris-says/0.2.0/ferris_says/fn.say.html

extern crate ferris_says;
use ferris_says::*;
use std::io::{ stdout, BufWriter };

fn main() {
  let stdout = stdout();
  let out = b"Hello fellow Rustaceans!";
  let width = 24;
  
  let mut writer = BufWriter::new(stdout.lock());
  say(out, width, &mut writer).unwrap();
}
```

```{r cleanup, echo=FALSE, results='hide'}
file.remove("cargo.toml")
```
