# % Generated by cnd: do not edit by hand

#' @name mark-cnd-conditions
#' @aliases mark-cnd-conditions mark:append_warning mark:assign_labels_error mark:base_conversion_error mark:bib_error mark:description_version_error mark:duplicate_error mark:expand_by_warning mark:fct_expand_seq_error mark:import_error mark:internal_error mark:list2df_warning mark:match_arg_no_match mark:match_param_error mark:md5_status mark:na_timezone_found_warning mark:not_available_error mark:numeric_datetime_tz_error mark:options_error mark:path_error mark:path_warning mark:percentile_rank_weights_length mark:reindex_error mark:reindex_warning mark:remove_labels_error mark:source_error mark:switch_error mark:timezone_not_found_error mark:view_labels_error append_warning assign_labels_error base_conversion_error bib_error description_version_error duplicate_error expand_by_warning fct_expand_seq_error import_error internal_error list2df_warning match_arg_no_match match_param_error md5_status na_timezone_found_warning not_available_error numeric_datetime_tz_error options_error path_error path_warning percentile_rank_weights_length reindex_error reindex_warning remove_labels_error source_error switch_error timezone_not_found_error view_labels_error mark:append_warning/warning mark:assign_labels_error/error mark:base_conversion_error/error mark:bib_error/error mark:description_version_error/error mark:duplicate_error/error mark:expand_by_warning/warning mark:fct_expand_seq_error/error mark:import_error/error mark:internal_error/error mark:list2df_warning/warning mark:match_arg_no_match/error mark:match_param_error/error mark:md5_status/condition mark:na_timezone_found_warning/warning mark:not_available_error/error mark:numeric_datetime_tz_error/error mark:options_error/error mark:path_error/error mark:path_warning/warning mark:percentile_rank_weights_length/error mark:reindex_error/error mark:reindex_warning/warning mark:remove_labels_error/error mark:source_error/error mark:switch_error/condition mark:timezone_not_found_error/error mark:view_labels_error/error
#' @title Conditions for `mark`
#'
#' @details
#'   The following conditions are defined in the `{mark}` package.
#'
#' @section `{cnd}`:
#'   These conditions are made with the [`{cnd}`][cnd-package] package though the
#'   use of [cnd::condition()].
#'
#' @section `{mark}` conditions:
#'
#'   \subsection{`mark:append_warning/warning`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:append_warning`}
#'     \item{type}{**warning**}
#'   }
#'   _no help documentation provided_
#'  }
#'   \subsection{`mark:assign_labels_error/error`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:assign_labels_error`}
#'     \item{type}{**error**}
#'   }
#'   `assign_labels_error`
#'
#'   **Columns not found**
#'   You can set `.missing` to `warn` to get a warning instead of an error, or `skip` to silently skip those labels.
#'
#'   **Malformed labels**
#'   If passing labels as `.ls`, `...` must be empty. Columns in `...` must be entered as `name = value`; `column = label`.
#'
#'   ```r
#'   # instead of this:
#'   assign_labels(df, a = 'AAA', .ls = list(b = 'BBB'))
#'
#'   # do this:
#'   assign_labels(df, a = 'AAA', b = 'BBB')
#'   # or this:
#'   assign_labels(df, .ls = list(a = 'AAA', b = 'BBB'))
#'   ```
#'   Labels must not be null; to remove lavels, use `remove_labels()`.
#'
#'   ```r
#'   # instead of this
#'   assign_labels(df, a = 'AAA', b = NULL)
#'
#'   # do this
#'   df <- assign_labels(df, a = 'AAA')
#'   df <- remove_labels(df, 'b')
#'   ```
#'  }
#'   \subsection{`mark:base_conversion_error/error`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:base_conversion_error`}
#'     \item{type}{**error**}
#'   }
#'   _no help documentation provided_
#'  }
#'   \subsection{`mark:bib_error/error`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:bib_error`}
#'     \item{type}{**error**}
#'   }
#'   _no help documentation provided_
#'  }
#'   \subsection{`mark:description_version_error/error`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:description_version_error`}
#'     \item{type}{**error**}
#'   }
#'   _no help documentation provided_
#'  }
#'   \subsection{`mark:duplicate_error/error`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:duplicate_error`}
#'     \item{type}{**error**}
#'   }
#'   _no help documentation provided_
#'  }
#'   \subsection{`mark:expand_by_warning/warning`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:expand_by_warning`}
#'     \item{type}{**warning**}
#'   }
#'   _no help documentation provided_
#'  }
#'   \subsection{`mark:fct_expand_seq_error/error`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:fct_expand_seq_error`}
#'     \item{type}{**error**}
#'   }
#'   _no help documentation provided_
#'  }
#'   \subsection{`mark:import_error/error`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:import_error`}
#'     \item{type}{**error**}
#'   }
#'   The object you are trying to import has already been assigned in the environment you are importing to.  Use the `overwrite` option to replace the object.
#'
#'   For example:
#'
#'   ```r
#'   # instead of
#'   foo <- NULL
#'   import('package', 'foo')
#'
#'   # do this
#'   foo <- NULL
#'   import('package', 'foo', overwrite = TRUE)
#'   ```
#'  }
#'   \subsection{`mark:internal_error/error`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:internal_error`}
#'     \item{type}{**error**}
#'   }
#'   Generic error to capture internal `{mark}` errors.  If any of these are encountered, please report an issue at <https://github.com/jmbarbone/mark/issues>
#'  }
#'   \subsection{`mark:list2df_warning/warning`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:list2df_warning`}
#'     \item{type}{**warning**}
#'   }
#'   _no help documentation provided_
#'  }
#'   \subsection{`mark:match_arg_no_match/error`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:match_arg_no_match`}
#'     \item{type}{**error**}
#'   }
#'   _no help documentation provided_
#'  }
#'   \subsection{`mark:match_param_error/error`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:match_param_error`}
#'     \item{type}{**error**}
#'   }
#'   _no help documentation provided_
#'  }
#'   \subsection{`mark:md5_status/condition`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:md5_status`}
#'     \item{type}{**condition**}
#'   }
#'   _no help documentation provided_
#'  }
#'   \subsection{`mark:na_timezone_found_warning/warning`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:na_timezone_found_warning`}
#'     \item{type}{**warning**}
#'   }
#'   _no help documentation provided_
#'  }
#'   \subsection{`mark:not_available_error/error`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:not_available_error`}
#'     \item{type}{**error**}
#'   }
#'   _no help documentation provided_
#'  }
#'   \subsection{`mark:numeric_datetime_tz_error/error`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:numeric_datetime_tz_error`}
#'     \item{type}{**error**}
#'   }
#'   ```r
#'   # Instead of this:
#'   diff_time(100, 200, tz = NULL)
#'
#'   # do this:
#'   diff_time(100, 200, tz = 'America/New_York')
#'
#'   # or:
#'   diff_time(100, 200, tz = 0)
#'   ```
#'  }
#'   \subsection{`mark:options_error/error`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:options_error`}
#'     \item{type}{**error**}
#'   }
#'   _no help documentation provided_
#'  }
#'   \subsection{`mark:path_error/error`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:path_error`}
#'     \item{type}{**error**}
#'   }
#'   _no help documentation provided_
#'  }
#'   \subsection{`mark:path_warning/warning`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:path_warning`}
#'     \item{type}{**warning**}
#'   }
#'   File creation cannot be performed when the path is an existing directory
#'  }
#'   \subsection{`mark:percentile_rank_weights_length/error`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:percentile_rank_weights_length`}
#'     \item{type}{**error**}
#'   }
#'   _no help documentation provided_
#'  }
#'   \subsection{`mark:reindex_error/error`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:reindex_error`}
#'     \item{type}{**error**}
#'   }
#'   _no help documentation provided_
#'  }
#'   \subsection{`mark:reindex_warning/warning`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:reindex_warning`}
#'     \item{type}{**warning**}
#'   }
#'   NA values in index may cause errors with expansion
#'
#'   `reindex()` will not match on NA values but instead will return a row of NAs
#'
#'   ```r
#'   x <- data.frame(index = c(1:2, NA, 4:5), values = letters[1:5])
#'   reindex(x, 'index', c(1, 2, 5))
#'   #>   index values
#'   #> 1     1      a
#'   #> 2     2      b
#'   #> 5     5      e
#'
#'   reindex(x, 'index', c(1, 2, 5, NA))
#'   #>      index values
#'   #> 1        1      a
#'   #> 2        2      b
#'   #> 5        5      e
#'   #> <NA>    NA   <NA>
#'   ```
#'  }
#'   \subsection{`mark:remove_labels_error/error`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:remove_labels_error`}
#'     \item{type}{**error**}
#'   }
#'   _no help documentation provided_
#'  }
#'   \subsection{`mark:source_error/error`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:source_error`}
#'     \item{type}{**error**}
#'   }
#'   _no help documentation provided_
#'  }
#'   \subsection{`mark:switch_error/condition`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:switch_error`}
#'     \item{type}{**condition**}
#'   }
#'   _no help documentation provided_
#'  }
#'   \subsection{`mark:timezone_not_found_error/error`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:timezone_not_found_error`}
#'     \item{type}{**error**}
#'   }
#'   When using a string for a timezone, this value must be found within `OlsonNames()`
#'  }
#'   \subsection{`mark:view_labels_error/error`}{
#'   \describe{
#'     \item{package}{`{mark}`}
#'     \item{class}{`mark:view_labels_error`}
#'     \item{type}{**error**}
#'   }
#'   This may be because you are using RStudio :  https://community.rstudio.com/t/view-is-causing-an-error/75297/4 You can try :  `utils::View(get_labels(x), title = "Labels")`
#'  }
#'
#' @seealso [cnd::cnd-package] [cnd::condition]
#' @keywords internal
#'
NULL
